<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $payment['receipt_no'] }} · MCI Fee Receipt</title>
<style>
:root{--ink:#07172d;--blue:#1769ff;--line:#dce4ea;--muted:#62778a}*{box-sizing:border-box}body{margin:0;background:#eef3f7;color:var(--ink);font-family:Arial,sans-serif}.toolbar{max-width:820px;margin:24px auto 12px;display:flex;justify-content:space-between}.toolbar a,.toolbar button{border:0;border-radius:9px;padding:11px 16px;text-decoration:none;font-weight:800;cursor:pointer}.toolbar a{background:#fff;color:var(--ink)}.toolbar button{background:var(--blue);color:#fff}.receipt{width:min(820px,calc(100% - 24px));margin:auto;background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 20px 60px #07172d1f}.head{display:flex;justify-content:space-between;align-items:center;padding:30px 36px;background:linear-gradient(120deg,#06182e,#1769ff);color:#fff}.identity{display:flex;gap:16px;align-items:center}.identity img{width:74px;height:74px;border-radius:50%;background:#fff}.identity h1{margin:0;font-size:22px}.identity p{margin:6px 0;color:#d8e8f5;font-size:12px}.receipt-no{text-align:right}.receipt-no small,.receipt-no b{display:block}.receipt-no small{color:#b9d3e7;font-size:10px;letter-spacing:1px}.receipt-no b{margin-top:7px}.body{padding:32px 36px}.student{display:grid;grid-template-columns:1fr 1fr;gap:22px;padding-bottom:24px}.block small{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.8px;margin-bottom:6px}.block b{font-size:15px}.block p{margin:5px 0;color:#52697c;font-size:12px;line-height:1.55}.payment{border:1px solid var(--line);border-radius:13px;overflow:hidden}.payment div{display:flex;justify-content:space-between;padding:14px 18px;border-bottom:1px solid var(--line)}.payment div:last-child{border:0}.payment span{color:#52697c}.payment .amount{background:#edf9f3}.payment .amount b{font-size:22px;color:#087548}.note{margin-top:18px;padding:13px;background:#f4f7fa;border-radius:9px;color:#52697c;font-size:12px}.foot{display:flex;justify-content:space-between;gap:20px;margin-top:38px;padding-top:20px;border-top:1px dashed #b9c6d1;font-size:11px;color:var(--muted)}.signature{text-align:center;min-width:180px}.signature:before{content:"";display:block;border-top:1px solid var(--ink);margin-bottom:7px}.disclaimer{text-align:center;padding:17px;background:#f4f7fa;color:#718599;font-size:10px}@media(max-width:600px){.head,.foot{align-items:flex-start;flex-direction:column}.student{grid-template-columns:1fr}.body,.head{padding:24px}.receipt-no{text-align:left}.toolbar{padding:0 12px}}@media print{body{background:#fff}.toolbar{display:none}.receipt{width:100%;border-radius:0;box-shadow:none}.head,.payment .amount,.disclaimer{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style>
</head><body>
<div class="toolbar"><a href="{{ route('admin.admissions.index') }}">← Back to Admissions</a><button onclick="window.print()">Print / Save PDF</button></div>
<article class="receipt">
<header class="head"><div class="identity"><img src="{{ asset('images/mci-logo.webp') }}" alt="MCI"><div><h1>Micro Computer Institute</h1><p>Education · Skill Development · Career</p></div></div><div class="receipt-no"><small>INSTALLMENT RECEIPT</small><b>{{ $payment['receipt_no'] }}</b></div></header>
<div class="body">
<section class="student"><div class="block"><small>Student / विद्यार्थी</small><b>{{ $application['student_name'] }}</b><p>Guardian: {{ $application['guardian_name'] }}<br>Phone: {{ $application['phone'] }}</p></div><div class="block"><small>Admission Details</small><b>{{ $application['application_no'] }}</b><p>Course: {{ $application['course_code'] }} — {{ $course?->title ?? 'Course' }}<br>Payment date: {{ \Carbon\Carbon::parse($payment['payment_date'])->format('d M Y') }}</p></div></section>
<section class="payment"><div class="amount"><span>Amount Received</span><b>₹{{ number_format((float)$payment['amount'],2) }}</b></div><div><span>Payment Mode</span><b>{{ strtoupper($payment['mode']) }}</b></div><div><span>Reference</span><b>{{ $payment['reference'] ?: '—' }}</b></div><div><span>Total Paid After Payment</span><b>₹{{ number_format((float)$application['paid_amount'],2) }}</b></div><div><span>Current Balance</span><b>₹{{ number_format((float)$application['balance_amount'],2) }}</b></div></section>
@if($payment['note'])<div class="note"><b>Note:</b> {{ $payment['note'] }}</div>@endif
<footer class="foot"><div>{{ $settings['address_line'] }}<br>{{ $settings['city'] }}, {{ $settings['district'] }}, {{ $settings['state'] }} – {{ $settings['pin'] }}<br>{{ $settings['phone'] }} · {{ $settings['email'] }}</div><div class="signature">Authorised Signature</div></footer>
</div><div class="disclaimer">Computer-generated installment receipt. Please retain it for future reference.</div>
</article></body></html>
