<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\AttendanceController;
use App\Http\Controllers\Admin\BackupController;
use App\Http\Controllers\Admin\AssignmentSubmissionController;
use App\Http\Controllers\Admin\AdmissionController as AdminAdmissionController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\CertificateController as AdminCertificateController;
use App\Http\Controllers\Admin\CommunicationController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DemoDataController;
use App\Http\Controllers\Admin\EnquiryController as AdminEnquiryController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\NoticeController;
use App\Http\Controllers\Admin\JobController;
use App\Http\Controllers\Admin\LearningResourceController;
use App\Http\Controllers\Admin\PracticeTestController;
use App\Http\Controllers\Admin\ProgressController;
use App\Http\Controllers\Admin\ProductionAuditController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ResultController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\AdmissionController;
use App\Http\Controllers\CertificateVerificationController;
use App\Http\Controllers\EnquiryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StudentPortalController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class,'index'])->name('home');
Route::post('/enquiry', [EnquiryController::class,'store'])->middleware('throttle:10,1')->name('enquiry.store');
Route::get('/certificate/verify', [CertificateVerificationController::class,'index'])->name('certificates.verify');
Route::get('/student/login', [StudentPortalController::class,'showLogin'])->name('student.login');
Route::post('/student/login', [StudentPortalController::class,'login'])->middleware('throttle:5,1')->name('student.login.submit');
Route::get('/student', [StudentPortalController::class,'dashboard'])->name('student.dashboard');
Route::post('/student/logout', [StudentPortalController::class,'logout'])->name('student.logout');
Route::post('/student/assignments', [StudentPortalController::class,'submitAssignment'])->middleware('throttle:10,1')->name('student.assignments.submit');
Route::get('/student/resources/{id}/download', [StudentPortalController::class,'downloadResource'])->name('student.resources.download');
Route::get('/student/practice-tests/{id}', [StudentPortalController::class,'practiceTest'])->name('student.practice.take');
Route::post('/student/practice-tests/{id}', [StudentPortalController::class,'submitPracticeTest'])->middleware('throttle:10,1')->name('student.practice.submit');
Route::get('/student/practice-results/{attemptId}', [StudentPortalController::class,'practiceResult'])->name('student.practice.result');
Route::get('/student/results/{id}/marksheet', [StudentPortalController::class,'marksheet'])->name('student.results.marksheet');
Route::get('/student/certificates/{id}/print', [StudentPortalController::class,'certificate'])->name('student.certificates.print');
Route::get('/apply-online', [AdmissionController::class,'create'])->name('admission.create');
Route::post('/apply-online', [AdmissionController::class,'store'])->middleware('throttle:5,1')->name('admission.store');

Route::prefix('admin')->name('admin.')->group(function () {
    Route::middleware('guest')->group(function () {
        Route::get('/login',[AuthController::class,'showLogin'])->name('login');
        Route::post('/login',[AuthController::class,'login'])->name('login.submit');
    });
    Route::middleware(['auth','admin'])->group(function () {
        Route::get('/',[DashboardController::class,'index'])->name('dashboard');
        Route::post('/logout',[AuthController::class,'logout'])->name('logout');
        Route::get('/profile',[ProfileController::class,'edit'])->name('profile.edit');
        Route::put('/profile',[ProfileController::class,'update'])->name('profile.update');
        Route::put('/profile/password',[ProfileController::class,'updatePassword'])->name('profile.password');
        Route::get('/certificates',[AdminCertificateController::class,'index'])->name('certificates.index');
        Route::post('/certificates',[AdminCertificateController::class,'store'])->name('certificates.store');
        Route::get('/certificates/{id}/print',[AdminCertificateController::class,'print'])->name('certificates.print');
        Route::delete('/certificates/{id}',[AdminCertificateController::class,'destroy'])->name('certificates.destroy');
        Route::get('/production-audit',[ProductionAuditController::class,'index'])->name('audit.index');
        Route::get('/demo-data',[DemoDataController::class,'index'])->name('demo-data.index');
        Route::post('/demo-data',[DemoDataController::class,'install'])->name('demo-data.install');
        Route::delete('/demo-data',[DemoDataController::class,'destroy'])->name('demo-data.destroy');
        Route::get('/production-audit.json',[ProductionAuditController::class,'json'])->name('audit.json');
        Route::get('/backup',[BackupController::class,'index'])->name('backup.index');
        Route::get('/backup/download',[BackupController::class,'download'])->name('backup.download');
        Route::post('/backup/restore',[BackupController::class,'restore'])->name('backup.restore');
        Route::get('/communications',[CommunicationController::class,'index'])->name('communications.index');
        Route::post('/communications',[CommunicationController::class,'store'])->name('communications.store');
        Route::delete('/communications/{id}',[CommunicationController::class,'destroy'])->name('communications.destroy');
        Route::get('/progress',[ProgressController::class,'index'])->name('progress.index');
        Route::get('/progress/{id}/print',[ProgressController::class,'print'])->name('progress.print');
        Route::get('/practice-tests',[PracticeTestController::class,'index'])->name('practice.index');
        Route::post('/practice-tests',[PracticeTestController::class,'store'])->name('practice.store');
        Route::patch('/practice-tests/{id}/toggle',[PracticeTestController::class,'toggle'])->name('practice.toggle');
        Route::delete('/practice-tests/{id}',[PracticeTestController::class,'destroy'])->name('practice.destroy');
        Route::get('/assignments',[AssignmentSubmissionController::class,'index'])->name('assignments.index');
        Route::patch('/assignments/{id}/review',[AssignmentSubmissionController::class,'review'])->name('assignments.review');
        Route::delete('/assignments/{id}',[AssignmentSubmissionController::class,'destroy'])->name('assignments.destroy');
        Route::get('/learning',[LearningResourceController::class,'index'])->name('learning.index');
        Route::post('/learning',[LearningResourceController::class,'store'])->name('learning.store');
        Route::patch('/learning/{id}/toggle',[LearningResourceController::class,'toggle'])->name('learning.toggle');
        Route::delete('/learning/{id}',[LearningResourceController::class,'destroy'])->name('learning.destroy');
        Route::get('/learning/{id}/download',[LearningResourceController::class,'download'])->name('learning.download');
        Route::get('/results',[ResultController::class,'index'])->name('results.index');
        Route::post('/results',[ResultController::class,'store'])->name('results.store');
        Route::get('/results/{id}/marksheet',[ResultController::class,'marksheet'])->name('results.marksheet');
        Route::delete('/results/{id}',[ResultController::class,'destroy'])->name('results.destroy');
        Route::get('/attendance',[AttendanceController::class,'index'])->name('attendance.index');
        Route::post('/attendance',[AttendanceController::class,'store'])->name('attendance.store');
        Route::get('/attendance-export',[AttendanceController::class,'export'])->name('attendance.export');
        Route::get('/attendance-report',[AttendanceController::class,'monthly'])->name('attendance.report');
        Route::get('/attendance-report-export',[AttendanceController::class,'monthlyExport'])->name('attendance.report.export');
        Route::get('/students',[AdminAdmissionController::class,'students'])->name('students.index');
        Route::post('/students/cards/print',[AdminAdmissionController::class,'studentCards'])->name('students.cards');
        Route::get('/students/{id}/card',[AdminAdmissionController::class,'studentCard'])->name('students.card');
        Route::patch('/students/{id}',[AdminAdmissionController::class,'updateStudent'])->name('students.update');
        Route::get('/admissions',[AdminAdmissionController::class,'index'])->name('admissions.index');
        Route::get('/fee-dues',[AdminAdmissionController::class,'feeDues'])->name('fees.dues');
        Route::get('/fee-dues-export',[AdminAdmissionController::class,'feeDuesExport'])->name('fees.dues.export');
        Route::get('/fee-collections',[AdminAdmissionController::class,'feeCollections'])->name('fees.collections');
        Route::get('/fee-collections-export',[AdminAdmissionController::class,'feeCollectionsExport'])->name('fees.collections.export');
        Route::get('/admissions-export',[AdminAdmissionController::class,'export'])->name('admissions.export');
        Route::patch('/admissions/{id}/status',[AdminAdmissionController::class,'updateStatus'])->name('admissions.status');
        Route::patch('/admissions/{id}/payment',[AdminAdmissionController::class,'updatePayment'])->name('admissions.payment');
        Route::post('/admissions/{id}/payments',[AdminAdmissionController::class,'addPayment'])->name('admissions.payments.store');
        Route::get('/admissions/{id}/payments/{paymentId}/receipt',[AdminAdmissionController::class,'paymentReceipt'])->name('admissions.payments.receipt');
        Route::get('/admissions/{id}/receipt',[AdminAdmissionController::class,'receipt'])->name('admissions.receipt');
        Route::delete('/admissions/{id}',[AdminAdmissionController::class,'destroy'])->name('admissions.destroy');
        Route::get('/jobs',[JobController::class,'index'])->name('jobs.index');
        Route::post('/jobs',[JobController::class,'store'])->name('jobs.store');
        Route::patch('/jobs/{id}/toggle',[JobController::class,'toggle'])->name('jobs.toggle');
        Route::delete('/jobs/{id}',[JobController::class,'destroy'])->name('jobs.destroy');
        Route::get('/notices',[NoticeController::class,'index'])->name('notices.index');
        Route::post('/notices',[NoticeController::class,'store'])->name('notices.store');
        Route::patch('/notices/{id}/toggle',[NoticeController::class,'toggle'])->name('notices.toggle');
        Route::delete('/notices/{id}',[NoticeController::class,'destroy'])->name('notices.destroy');
        Route::get('/gallery',[GalleryController::class,'index'])->name('gallery.index');
        Route::post('/gallery',[GalleryController::class,'store'])->name('gallery.store');
        Route::patch('/gallery/{id}/toggle',[GalleryController::class,'toggle'])->name('gallery.toggle');
        Route::delete('/gallery/{id}',[GalleryController::class,'destroy'])->name('gallery.destroy');
        Route::get('/settings',[SettingsController::class,'edit'])->name('settings.edit');
        Route::put('/settings',[SettingsController::class,'update'])->name('settings.update');
        Route::get('/courses',[CourseController::class,'index'])->name('courses.index');
        Route::post('/courses',[CourseController::class,'store'])->name('courses.store');
        Route::put('/courses/{course}',[CourseController::class,'update'])->name('courses.update');
        Route::patch('/courses/{course}/toggle',[CourseController::class,'toggle'])->name('courses.toggle');
        Route::delete('/courses/{course}',[CourseController::class,'destroy'])->name('courses.destroy');
        Route::get('/enquiries',[AdminEnquiryController::class,'index'])->name('enquiries.index');
        Route::get('/enquiries-export',[AdminEnquiryController::class,'export'])->name('enquiries.export');
        Route::patch('/enquiries/{enquiry}/status',[AdminEnquiryController::class,'updateStatus'])->name('enquiries.status');
        Route::delete('/enquiries/{enquiry}',[AdminEnquiryController::class,'destroy'])->name('enquiries.destroy');
    });
});
Route::redirect('/login','/admin/login')->name('login');
