<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MCI Student ID Cards</title>
<style>
@page{size:A4 portrait;margin:7mm}*{box-sizing:border-box}body{margin:0;background:#eef2f5;color:#07172d;font-family:Arial,sans-serif}.toolbar{max-width:900px;margin:18px auto 10px;display:flex;justify-content:space-between;gap:10px}.toolbar a,.toolbar button{border:0;border-radius:8px;padding:11px 15px;font-weight:800;text-decoration:none;cursor:pointer}.toolbar a{background:#fff;color:#07172d}.toolbar button{background:#078b55;color:#fff}.a4{width:196mm;min-height:283mm;margin:auto;background:#fff;padding:12mm 8mm;box-shadow:0 14px 45px #07172d20}.student-pair{display:grid;grid-template-columns:85.6mm 85.6mm;gap:7mm;justify-content:center;margin-bottom:18mm;break-inside:avoid}.id-card{position:relative;width:85.6mm;height:54mm;overflow:hidden;border:1px solid #123f73;border-radius:3mm;background:#fff;box-shadow:0 2mm 5mm #07172d20}.front{display:grid;grid-template-rows:15mm 1fr 7mm}.id-head{display:flex;align-items:center;gap:3mm;padding:2mm 3mm;background:linear-gradient(115deg,#06254a,#0b8f58);color:#fff}.id-head img{width:11mm;height:11mm;border-radius:50%;background:#fff;object-fit:contain}.id-head h1{margin:0;font-size:4.3mm;line-height:1}.id-head p{margin:1mm 0 0;font-size:2.1mm;letter-spacing:.25mm}.front-body{display:grid;grid-template-columns:25mm 1fr 18mm;gap:2.5mm;padding:3mm}.photo{width:23mm;height:28mm;border:1px solid #bad0df;border-radius:1.5mm;object-fit:cover;background:#edf3f6}.photo-fallback{display:grid;place-items:center;font-size:8mm;font-weight:900;color:#0b8f58}.student-info h2{font-size:4.5mm;margin:0 0 2mm;color:#06254a}.student-info dl{margin:0;display:grid;grid-template-columns:14mm 1fr;gap:1mm;font-size:2.4mm}.student-info dt{color:#607588}.student-info dd{margin:0;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.qr img,.back-qr img{width:17mm;height:17mm}.qr small{display:block;text-align:center;font-size:1.7mm}.id-foot{display:flex;justify-content:space-between;align-items:center;padding:1.5mm 3mm;background:#f2c94c;font-size:2.2mm;font-weight:700}.back{padding:4mm;background:linear-gradient(145deg,#f8fbfa,#eaf5ef)}.back h2{text-align:center;margin:0 0 2mm;font-size:4mm;color:#0b8f58}.back-grid{display:grid;grid-template-columns:1fr 21mm;gap:3mm}.rules{margin:0;padding-left:4mm;font-size:2.35mm;line-height:1.5}.back-qr{text-align:center;font-size:1.8mm}.contact{margin-top:3mm;padding-top:2.5mm;border-top:1px dashed #8ca2b3;font-size:2.2mm;line-height:1.45}.signature{position:absolute;right:4mm;bottom:4mm;width:27mm;text-align:center;border-top:1px solid #07172d;padding-top:1mm;font-size:2mm}.cut{position:absolute;inset:auto 0 0;text-align:center;color:#8093a2;font-size:1.6mm}@media print{body{background:#fff}.toolbar{display:none}.a4{width:100%;min-height:auto;padding:8mm 3mm;box-shadow:none}.id-card,.id-head,.id-foot,.back{-webkit-print-color-adjust:exact;print-color-adjust:exact}.student-pair{margin-bottom:14mm}}
</style></head><body>
<div class="toolbar"><a href="{{ route('admin.students.index') }}">← Back to Students</a><button onclick="window.print()">Print A4 / Save PDF</button></div>
<main class="a4">
@foreach($students as $student)
@php($course=$student['course_record'] ?? null)
@php($qrData=urlencode(route('student.login').'?application='.$student['application_no']))
<section class="student-pair">
<article class="id-card front"><header class="id-head"><img src="{{ asset('images/mci-logo.webp') }}" alt="MCI"><div><h1>Micro Computer Institute</h1><p>STUDENT IDENTITY CARD</p></div></header>
<div class="front-body"><div>@if(!empty($student['photo_path']))<img class="photo" src="{{ asset($student['photo_path']) }}" alt="{{ $student['student_name'] }}">@else<div class="photo photo-fallback">{{ strtoupper(substr($student['student_name'],0,1)) }}</div>@endif</div>
<div class="student-info"><h2>{{ $student['student_name'] }}</h2><dl><dt>Roll No.</dt><dd>{{ $student['roll_no'] ?? $student['application_no'] }}</dd><dt>Course</dt><dd>{{ $student['course_code'] }}</dd><dt>Batch</dt><dd>{{ $student['batch_name'] ?? '—' }}</dd><dt>Valid</dt><dd>{{ $student['student_status'] ?? 'Active' }}</dd></dl></div>
<div class="qr"><img src="https://api.qrserver.com/v1/create-qr-code/?size=140x140&amp;data={{ $qrData }}" alt="Student QR"><small>SCAN</small></div></div>
<footer class="id-foot"><span>{{ $settings['phone'] }}</span><span>{{ $student['application_no'] }}</span></footer></article>
<article class="id-card back"><h2>INSTRUCTIONS / निर्देश</h2><div class="back-grid"><ul class="rules"><li>This card is non-transferable.</li><li>Carry the card during classes and examinations.</li><li>Return a lost card to Micro Computer Institute.</li><li>Misuse may result in cancellation.</li><li>यह कार्ड केवल संबंधित विद्यार्थी के लिए मान्य है।</li></ul><div class="back-qr"><img src="https://api.qrserver.com/v1/create-qr-code/?size=140x140&amp;data={{ $qrData }}" alt="Verification QR"><b>Verify Student</b></div></div>
<div class="contact"><b>Micro Computer Institute</b><br>{{ $settings['address_line'] }}, {{ $settings['city'] }}, {{ $settings['district'] }} – {{ $settings['pin'] }}<br>Phone: {{ $settings['phone'] }} · {{ $settings['email'] }}</div><div class="signature">Authorised Signature</div><div class="cut">Front ↔ Back · Cut along card border</div></article>
</section>
@endforeach
</main></body></html>