<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Student Portal · {{ $student['student_name'] }}</title><link rel="stylesheet" href="{{ asset('css/student-portal.css') }}"><link rel="stylesheet" href="{{ asset('css/student-assessment.css') }}"></head><body class="portal-body">
<header class="portal-header"><a class="portal-brand" href="{{ route('student.dashboard') }}"><img src="{{ asset('images/mci-logo.webp') }}" alt="MCI"><span><b>MCI Student Portal</b><small>Computer Education</small></span></a><form method="post" action="{{ route('student.logout') }}">@csrf<button>Logout</button></form></header>
<main class="portal-shell"><section class="student-welcome"><div><small>WELCOME BACK</small><h1>{{ $student['student_name'] }}</h1><p>{{ $student['course_code'] }} — {{ $course?->title ?? 'Course' }}</p></div><div class="student-identity"><span>Application <b>{{ $student['application_no'] }}</b></span><span>Roll No. <b>{{ $student['roll_no'] ?? 'Not assigned' }}</b></span><span>Batch <b>{{ $student['batch_name'] ?? $student['preferred_time'] ?? 'Not assigned' }}</b></span></div></section>
<nav class="portal-nav"><a href="#notifications">Notifications</a><a href="#progress">Progress</a><a href="#fees">Fees</a><a href="#attendance">Attendance</a><a href="#learning">Study Materials</a><a href="#practice">Practice Tests</a><a href="#results">Results</a><a href="#certificates">Certificates</a></nav>
<section class="portal-panel notification-center" id="notifications"><div class="portal-title"><div><small>UPDATES & REMINDERS</small><h2>Notification Center</h2></div><span class="portal-status status-paid">{{ count($notifications) }} updates</span></div>
@if(count($notifications))<div class="student-notifications">@foreach($notifications as $notification)<article class="notification-{{ $notification['type'] }}"><div class="notification-symbol">{{ $notification['type']==='fee'?'₹':($notification['type']==='assignment'?'✓':($notification['type']==='result'?'★':'!')) }}</div><div><small>{{ strtoupper($notification['type']) }} @if($notification['date']) · {{ \Carbon\Carbon::parse($notification['date'])->format('d M Y') }}@endif</small><h3>{{ $notification['title'] }}</h3>@if($notification['title_hi'])<b>{{ $notification['title_hi'] }}</b>@endif<p>{{ $notification['message'] }}</p></div>@if($notification['link'])<a href="{{ $notification['link'] }}" @if(str_starts_with($notification['link'],'http')) target="_blank" rel="noopener noreferrer" @endif>Open →</a>@endif</article>@endforeach</div>@else<p class="portal-empty">You have no new notifications.</p>@endif</section>
<section class="portal-stats"><article><small>Course Fee</small><strong>₹{{ number_format($student['course_fee'],2) }}</strong></article><article><small>Total Paid</small><strong>₹{{ number_format($student['paid_amount'],2) }}</strong></article><article><small>Balance Due</small><strong class="{{ $student['balance_amount']>0?'warning':'success' }}">₹{{ number_format($student['balance_amount'],2) }}</strong></article><article><small>Attendance</small><strong>{{ number_format($attendanceRate,1) }}%</strong></article></section>
<section class="portal-panel student-progress-panel" id="progress"><div class="portal-title"><div><small>YOUR PERFORMANCE</small><h2>Overall Learning Progress</h2></div><span class="portal-status status-paid">{{ $progress['grade'] }}</span></div><div class="student-progress-grid"><div class="student-overall"><strong>{{ number_format($progress['overall'],1) }}%</strong><small>Overall Progress</small></div><div class="student-metrics"><span>Attendance<b>{{ $progress['attendance_rate']===null?'—':$progress['attendance_rate'].'%' }}</b></span><span>Assignments<b>{{ $progress['assignment_average']===null?'—':$progress['assignment_average'].'%' }}</b></span><span>Practice Tests<b>{{ $progress['practice_average']===null?'—':$progress['practice_average'].'%' }}</b></span><span>Exams<b>{{ $progress['exam_average']===null?'—':$progress['exam_average'].'%' }}</b></span></div></div><p class="progress-note">Progress available records के average पर आधारित है और नई activity के साथ automatically update होता है।</p></section>
<section class="portal-panel" id="fees"><div class="portal-title"><div><small>FEE ACCOUNT</small><h2>Payment History</h2></div><span class="portal-status status-{{ $student['payment_status'] }}">{{ ucfirst($student['payment_status']) }}</span></div>
@if(count($student['payments']))<div class="portal-table-wrap"><table><thead><tr><th>Date</th><th>Receipt</th><th>Mode</th><th>Reference</th><th>Amount</th></tr></thead><tbody>@foreach($student['payments'] as $payment)<tr><td>{{ \Carbon\Carbon::parse($payment['payment_date'])->format('d M Y') }}</td><td>{{ $payment['receipt_no'] }}</td><td>{{ strtoupper($payment['mode']) }}</td><td>{{ $payment['reference'] ?: '—' }}</td><td><b>₹{{ number_format($payment['amount'],2) }}</b></td></tr>@endforeach</tbody></table></div>@elseif($student['paid_amount']>0)<p class="portal-empty">Opening paid amount: ₹{{ number_format($student['paid_amount'],2) }}. Future transactions will appear here.</p>@else<p class="portal-empty">No fee payment recorded yet.</p>@endif</section>
<section class="portal-panel" id="attendance"><div class="portal-title"><div><small>ATTENDANCE</small><h2>Your Attendance</h2></div><div class="attendance-chips"><span class="present">Present {{ $attendanceCounts['present'] ?? 0 }}</span><span class="absent">Absent {{ $attendanceCounts['absent'] ?? 0 }}</span><span class="leave">Leave {{ $attendanceCounts['leave'] ?? 0 }}</span></div></div>
@if(count($attendance))<div class="attendance-calendar">@foreach(array_slice($attendance,0,31) as $row)<div class="{{ $row['status'] }}"><b>{{ \Carbon\Carbon::parse($row['date'])->format('d') }}</b><small>{{ \Carbon\Carbon::parse($row['date'])->format('M') }}</small><span>{{ ucfirst($row['status']) }}</span></div>@endforeach</div>@else<p class="portal-empty">Attendance records are not available yet.</p>@endif</section>
<section class="portal-panel" id="learning"><div class="portal-title"><div><small>COURSE RESOURCES</small><h2>Study Materials & Assignments</h2></div><span class="portal-status status-paid">{{ count($learningResources) }} available</span></div>
@if(count($learningResources))<div class="learning-portal-grid">@foreach($learningResources as $resource)<article class="portal-resource type-{{ $resource['type'] }}">
<div class="portal-resource-icon">{{ $resource['is_pinned'] ? '★' : ($resource['type']==='video' ? '▶' : ($resource['type']==='assignment' ? '✓' : '▰')) }}</div>
<div><div class="portal-resource-meta"><span>{{ strtoupper($resource['type']) }}</span>@if($resource['is_pinned'])<b>PINNED</b>@endif @if($resource['due_date'])<strong>Due {{ \Carbon\Carbon::parse($resource['due_date'])->format('d M Y') }}</strong>@endif</div><h3>{{ $resource['title'] }}</h3><p>{{ $resource['description'] ?: 'Open the resource to continue learning.' }}</p></div>
<a href="{{ !empty($resource['file_path']) ? route('student.resources.download',$resource['id']) : $resource['link_url'] }}" target="_blank" rel="noopener noreferrer">{{ !empty($resource['file_path']) ? 'Download PDF ↓' : 'Open Resource ↗' }}</a>
@if($resource['type']==='assignment')@php($submission=$assignmentSubmissions->get($resource['id']))<div class="assignment-submit-area">
@if($submission)<div class="student-submission-status status-{{ $submission['status'] }}"><b>{{ $submission['status']==='reviewed' ? 'Reviewed · '.$submission['marks'].'/100' : 'Submitted · Awaiting Review' }}</b>@if($submission['feedback'])<p>Teacher feedback: {{ $submission['feedback'] }}</p>@endif</div>@endif
<form method="post" action="{{ route('student.assignments.submit') }}">@csrf<input type="hidden" name="resource_id" value="{{ $resource['id'] }}"><textarea name="answer_text" rows="2" maxlength="5000" placeholder="Write your answer or submission note...">{{ $submission['answer_text'] ?? '' }}</textarea><input type="url" name="submission_url" value="{{ $submission['submission_url'] ?? '' }}" placeholder="https://drive.google.com/... (optional work link)"><button>{{ $submission ? 'Resubmit Assignment' : 'Submit Assignment' }}</button></form>
</div>@endif
</article>@endforeach</div>@else<p class="portal-empty">No study material has been published for your course yet.</p>@endif</section>
<section class="portal-panel" id="practice"><div class="portal-title"><div><small>ONLINE PRACTICE</small><h2>MCQ Tests & Instant Results</h2></div><span class="portal-status status-paid">{{ count($practiceTests) }} available</span></div>
<div class="assessment-summary"><span><b>{{ $assessment['completed'] }}/5</b> Tests Completed</span><span><b>{{ number_format($assessment['percentage'],1) }}%</b> Weighted Score</span><span><b>{{ $assessment['grade'] }}</b> Current Grade</span><p>Final marksheet और certificate सभी 5 assessments पूरा करके qualifying score पाने पर automatically जारी होंगे।</p></div>
@if(count($practiceTests))<div class="practice-portal-grid">@foreach($practiceTests as $test)@php($attempt=$practiceAttempts->get($test['id']))<article><div class="practice-test-icon">{{ ($test['assessment_type']??'practice')==='final'?'F':(($test['assessment_type']??'practice')==='terminal'?'T':'P') }}</div><div><small>{{ strtoupper($test['assessment_type']??'practice') }} · WEIGHT {{ $test['assessment_weight']??0 }}% · {{ count($test['questions']) }} QUESTIONS · {{ $test['duration_minutes'] }} MINUTES</small><h3>{{ $test['title'] }}</h3><p>Pass percentage: {{ $test['pass_percentage'] }}%@if($attempt) · Best score: <b class="{{ $attempt['status'] }}">{{ number_format($attempt['percentage'],1) }}%</b>@endif</p></div><a href="{{ route('student.practice.take',$test['id']) }}">{{ $attempt?'Try Again':'Start Test' }} →</a></article>@endforeach</div>@else<p class="portal-empty">No online practice test has been published for your course yet.</p>@endif</section>
<section class="portal-panel" id="results"><div class="portal-title"><div><small>ACADEMIC RESULTS</small><h2>Exams & Marksheets</h2></div></div>
@if(count($results))<div class="result-portal-grid">@foreach($results as $result)<article><div class="result-percent {{ $result['result_status'] }}"><strong>{{ number_format($result['percentage'],1) }}%</strong><small>Grade {{ $result['grade'] }}</small></div><div><h3>{{ $result['exam_name'] }}</h3><p>{{ \Carbon\Carbon::parse($result['exam_date'])->format('d M Y') }} · {{ strtoupper($result['result_status']) }}</p><small>{{ $result['result_no'] }}</small></div><a href="{{ route('student.results.marksheet',$result['id']) }}" target="_blank">View Marksheet</a></article>@endforeach</div>@else<p class="portal-empty">No examination result has been published yet.</p>@endif</section>
<section class="portal-panel" id="certificates"><div class="portal-title"><div><small>ACHIEVEMENTS</small><h2>Your Certificates</h2></div></div>
@if(count($certificates))<div class="certificate-portal-grid">@foreach($certificates as $certificate)<article><div class="cert-symbol">◇</div><div><h3>{{ $certificate['title'] }}</h3><p>{{ ucwords($certificate['type']) }} · {{ \Carbon\Carbon::parse($certificate['issue_date'])->format('d M Y') }}</p><small>{{ $certificate['verification_code'] }}</small></div><div><a href="{{ route('student.certificates.print',$certificate['id']) }}" target="_blank">Print</a><a href="{{ route('certificates.verify',['code'=>$certificate['verification_code']]) }}" target="_blank">Verify</a></div></article>@endforeach</div>@else<p class="portal-empty">No certificate has been issued yet.</p>@endif</section>
<footer class="portal-footer">Micro Computer Institute · Student records are private and session-protected.</footer></main></body></html>
