@extends('admin.layout')
@section('title','Communications & Messaging')
@section('content')
<div class="communication-grid">
<section class="panel template-compose"><div class="panel-title"><div><small>REUSABLE MESSAGE</small><h2>Create communication template</h2></div></div><form method="post" action="{{ route('admin.communications.store') }}">@csrf<div class="form-grid"><label>Template Name<input name="name" required maxlength="120"></label><label>Channel<select name="channel"><option value="both">WhatsApp + Email</option><option value="whatsapp">WhatsApp</option><option value="email">Email</option></select></label><label>Category<select name="category"><option value="general">General</option><option value="fee">Fee</option><option value="assignment">Assignment</option><option value="result">Result</option></select></label><label class="full">Email Subject<input name="subject" required maxlength="180" value="Important update from MCI"></label><label class="full">Message Body<textarea name="body" rows="5" required maxlength="2000" placeholder="Dear {student_name}, ..."></textarea></label></div><p class="template-vars">Variables: <b>{student_name}</b> <b>{course}</b> <b>{application_no}</b> <b>{balance}</b> <b>{portal_url}</b></p><button class="btn">Save Template</button></form></section>
<section class="panel template-library"><div class="panel-title"><div><small>MESSAGE LIBRARY</small><h2>{{ count($templates) }} templates</h2></div></div><div class="template-list">@foreach($templates as $template)<article class="{{ $selected&&$selected['id']===$template['id']?'selected':'' }}"><div><small>{{ strtoupper($template['category']) }} · {{ strtoupper($template['channel']) }}</small><h3>{{ $template['name'] }}</h3><p>{{ $template['body'] }}</p></div><a href="{{ route('admin.communications.index',['template'=>$template['id']]) }}">Use</a><form method="post" action="{{ route('admin.communications.destroy',$template['id']) }}" onsubmit="return confirm('Delete this template?')">@csrf @method('DELETE')<button>Delete</button></form></article>@endforeach</div></section>
</div>
<section class="panel communication-students"><div class="panel-title"><div><small>QUICK MESSAGING</small><h2>{{ $selected['name'] ?? 'Select a template' }}</h2></div></div><form class="communication-filter" method="get"><input type="hidden" name="template" value="{{ $selected['id'] ?? '' }}"><input name="search" value="{{ request('search') }}" placeholder="Student, application no. or phone..."><select name="course"><option value="">All Courses</option>@foreach($courses as $course)<option value="{{ $course->code }}" @selected(request('course')===$course->code)>{{ $course->code }}</option>@endforeach</select><label><input type="checkbox" name="dues" value="1" @checked(request('dues'))> Fee dues only</label><button class="soft-btn">Filter</button><a href="{{ route('admin.communications.index',['template'=>$selected['id']??'']) }}">Clear</a></form>
@if(count($students))<div class="communication-student-list">@foreach($students as $student)<article><div><small>{{ $student['application_no'] }} · {{ $student['course_code'] }}</small><h3>{{ $student['student_name'] }}</h3><p>{{ $student['phone'] }} @if($student['email']) · {{ $student['email'] }}@endif</p></div><div class="message-preview"><b>{{ $student['rendered']['subject'] }}</b><p>{{ $student['rendered']['body'] }}</p></div><div class="message-actions">@if($student['whatsapp_phone'])<a class="whatsapp" href="https://wa.me/{{ $student['whatsapp_phone'] }}?text={{ urlencode($student['rendered']['body']) }}" target="_blank" rel="noopener noreferrer">WhatsApp</a>@endif @if($student['email'])<a class="email" href="mailto:{{ $student['email'] }}?subject={{ urlencode($student['rendered']['subject']) }}&body={{ urlencode($student['rendered']['body']) }}">Email</a>@endif</div></article>@endforeach</div>@else<div class="empty"><b>No matching admitted students</b><p>Change the search or course filter.</p></div>@endif</section>
@endsection
