@extends('admin.layout')
@section('title','Data Backup & Recovery')
@section('content')
<div class="cards backup-summary"><div class="card blue"><small>Runtime Data Files</small><strong>{{ count($status['files']) }}</strong></div><div class="card green"><small>Total Data Size</small><strong>{{ number_format($status['total_size']/1024,1) }} KB</strong></div><div class="card purple"><small>Courses</small><strong>{{ $status['courses'] }}</strong></div><div class="card orange"><small>Enquiries</small><strong>{{ $status['enquiries'] }}</strong></div></div>
<div class="backup-grid">
<section class="panel backup-download"><div class="panel-title"><div><small>COMPLETE DATA COPY</small><h2>Download secure backup</h2></div></div><div class="backup-icon">⤓</div><p>एक signed backup file में students, fee transactions, attendance, tests, assignments, results, certificates, website settings, notices, jobs, courses और enquiries सुरक्षित होंगे।</p><a class="btn" href="{{ route('admin.backup.download') }}">Download Full Backup</a><ul><li>Passwords और .env credentials backup में शामिल नहीं होते।</li><li>Backup इसी MCI installation की APP_KEY से verified है।</li><li>File को Google Drive या सुरक्षित computer folder में रखें।</li></ul></section>
<section class="panel backup-restore"><div class="panel-title"><div><small>DISASTER RECOVERY</small><h2>Restore from backup</h2></div></div><div class="restore-warning"><b>Restore वर्तमान records को backup के records से बदल देगा।</b><span>Restore से पहले system वर्तमान data का private automatic snapshot बनाता है और अंतिम 10 snapshots सुरक्षित रखता है।</span></div><form method="post" action="{{ route('admin.backup.restore') }}" enctype="multipart/form-data">@csrf<label>Choose MCI backup file<input type="file" name="backup_file" accept=".json,application/json" required></label><label>Safety Confirmation<input name="confirmation" placeholder="Type: RESTORE MCI DATA" required autocomplete="off"></label><button class="btn danger-btn" onclick="return confirm('Restore all MCI data from this backup?')">Verify & Restore Data</button></form></section>
</div>
<section class="panel backup-files"><div class="panel-title"><div><small>BACKUP COVERAGE</small><h2>Protected data files</h2></div></div><div class="backup-file-list">@foreach($status['files'] as $file)<article><span class="{{ $file['exists']?'ready':'empty' }}">{{ $file['exists']?'✓':'○' }}</span><div><b>{{ $file['name'] }}</b><small>{{ $file['exists']?number_format($file['size']/1024,1).' KB · Updated '.date('d M Y, h:i A',$file['modified']):'No runtime data yet' }}</small></div></article>@endforeach</div></section>
@endsection
